### ISSUE TITLE
Value of boolean fields is not shown

### ISSUE THREAD

**Issue by Strahlemann** [qwtel/sqlite-viewer-vscode#11]
When looking at a table through vscode then the row values for boolean columns are not shown.
The filter on the top still reacts when searching for 0 or 1 but the values themselves are not displayed.

![Screen Shot 2022-06-30 at 12 41 53](https://user-images.githubusercontent.com/5476762/176732319-dac22d28-10b6-4ea4-87cd-c6dd48f01e26.png)
![Screen Shot 2022-06-30 at 12 40 04](https://user-images.githubusercontent.com/5476762/176732337-88717f8d-db90-4ef2-ada7-30399f8bf5c0.png)

**Comment by luabida** [comment]
same error here
![image](https://user-images.githubusercontent.com/82233055/206703719-90bdad9f-525f-48c3-a8d8-ba3176120fb2.png)

**Comment by naourass** [comment]
Same issue here.

**Comment by qwtel** [comment]
Should be fixed in latest prerelease 0.2.1

**Comment by qwtel** [comment]
Should be fixed in 0.2.3
