### ISSUE TITLE
Publish this repo in https://open-vsx.org/

### ISSUE THREAD

**Issue by idantr** [qwtel/sqlite-viewer-vscode#12]
Hi @qwtel 

Can this vscode extension be publish in https://open-vsx.org/ 
I cannot use extensions from the MS marketplace in our project, only stuff from open-vsx
also is it possible to upload the vsix to install in this repo under releases as is cutomert in other vscode extensions repos

if one of the 2 option above are implemented this is ok with us

Regards
Idan.

**Comment by qwtel** [comment]
Should be available now: https://open-vsx.org/extension/qwtel/sqlite-viewer
