### ISSUE TITLE
Expand extension association

### ISSUE THREAD

**Issue by Maruchero** [qwtel/sqlite-viewer-vscode#14]
Awesome extension! But why can't it be compatible with more file extensions? 

There are many different extensions for sqlite files, as told by [Wikipedia](https://en.wikipedia.org/wiki/SQLite):
- .sqlite
- .sqlite3
- .db
- .db3
- .s3db
- .sl3

**Comment by qwtel** [comment]
Extensions like .db are too generic for a hard association with sqlite viewer. However, you can define custom file associations through vscode itself.

**Comment by Maruchero** [comment]
Ok, thanks
