### ISSUE TITLE
No such module: fts5

### ISSUE THREAD

**Issue by PeterStavrou** [qwtel/sqlite-viewer-vscode#16]
Excellent extensions!
When trying to view a wagtail sqlite3 database an error occurs: No such module: fts5

**Comment by ssteinerx** [comment]
I'm having same problem with closure table extension.

Is there or can there be a way to load extensions?

**Comment by qwtel** [comment]
Should be fixed in latest prerelease version 0.2.2

**Comment by qwtel** [comment]
Fixed in 0.2.3
