### ISSUE TITLE
cannot open sqlite file on remote host

### ISSUE THREAD

**Issue by TheMasterOfMagic** [qwtel/sqlite-viewer-vscode#2]
when I use vscode to ssh-connect to a remote host and open a .sqlite3 file on it, the open action failed and the message below showed

![image](https://user-images.githubusercontent.com/25054321/138683618-216f2ec4-c6e7-4375-80ea-93fe7694b59f.png)

not sure if I'm using it properly 👀

**Comment by qwtel** [comment]
The extension was misinterpreted by vscode as a remote extension (thereby forcing you to install it on the ssh host). Now configured as UI extension. Should work in version 0.0.24. Thanks for reporting this!
