### ISSUE TITLE
Bug Reported： vscode will crash when opening a large sqlite file

### ISSUE THREAD

**Issue by benzenesulfonic-acid** [qwtel/sqlite-viewer-vscode#25]
SQLite Viewer v0.1.5
VS Code 1.75.0

When I open a large sqlite file（about 1.5G, 12k rows） ，vscode will crash. It will use more than 6G RAM before program close. It seems a  out of memory problem.

**Comment by qwtel** [comment]
Your suspicion is correct. Due to limitations in vscode's `fs` library, sqlite files have to be read into memory.

**Comment by bachittle** [comment]
could there perhaps be configuration settings for this? I would rather it tell me it can't be opened than having all my vscode instances crash.

**Comment by qwtel** [comment]
Added a setting for max size
