### ISSUE TITLE
Feature Request: Setting to add extra extensions besides .sqlite

### ISSUE THREAD

**Issue by zholmes1** [qwtel/sqlite-viewer-vscode#27]
A dependency in my codebase requires that my SQLite databases files have a .db file extension. I'd love to be able to use this VSCode extension on these files, but it only recognizes .sqlite files and there's no setting to add more extensions.

**Comment by qwtel** [comment]
This is a feature if vscode and already supported. Use the "open with" dialog to add a permanent file association.

**Comment by zholmes1** [comment]
Amazing, thanks so much for the quick reply!
