### ISSUE TITLE
Allow copying data from table view, have details view include newlines

### ISSUE THREAD

**Issue by alexkreidler** [qwtel/sqlite-viewer-vscode#29]
When I right click on a row in the table view it shows Cut, Copy, and Paste options, but none of them work. It would be great if we could select entire rows and than copy the data in a tab-separated format, which would allow copying and pasting into tools like Google Sheets and Excel. [Glide Data Grid](https://github.com/glideapps/glide-data-grid) is a good React component that supports this and many other features out of the box.

Also, when I open the details view for a row, and then copy the text from one field, it does not include newlines. (they are removed, so words on separate lines are combined). Maybe this is a limitation of the VSCode short text box? Maybe you could also have a button that opens a text value in an editor in VSCode, because I'm storing fairly long document-like things in some fields I'd like to be able to read comfortably and edit.

Thanks for this great extension, it is the best and fastest one I've tried, and works great with VSCode Remote SSH mode!

**Comment by qwtel** [comment]
The newline bug has been fixed in latest preview, thanks for reporting.

> It would be great if we could select entire rows and than copy the data in a tab-separated format, which would allow copying and pasting into tools like Google Sheets and Excel

This is actually implemented and shipped, but it is curently not documented and only unlocked for monthly sponsors. 

> Maybe you could also have a button that opens a text value in an editor in VSCode, because I'm storing fairly long document-like things in some fields I'd like to be able to read comfortably and edit

I've been thinking about ways to improve viewing document-like text fields (also JSON fields) but haven't had time to work on it.

Editing is currently unfeasilbe due to limitations in the workspace `fs` module.

**Comment by qwtel** [comment]
> Maybe this is a limitation of the VSCode short text box? it was 😉
