### ISSUE TITLE
Databases that use the Rtree extension do not load

### ISSUE THREAD

**Issue by palmerj** [qwtel/sqlite-viewer-vscode#3]
Databases that use the [Rtree](https://www.sqlite.org/rtree.html) module do not load.

Example [nz-primary-parcels-waiheke.sqlite.zip](https://github.com/qwtel/sqlite-viewer-vscode/files/7631831/nz-primary-parcels-waiheke.sqlite.zip)

**Comment by qwtel** [comment]
Thanks for reporting this. I'm showing an error message for now. 
I'll be looking into compiling SQLite with the extension enabled later.
