### ISSUE TITLE
add *.db to custom editor sqlite-viewer.view filename pattern

### ISSUE THREAD

**Issue by CoreBodyTemp** [qwtel/sqlite-viewer-vscode#31]
my files are usually stored as .db, it would be great if the sqlite-viewer would support opening the .db files without first renaming them to .sqlite

**Comment by kentcdodds** [comment]
I would also like this as a default.

However, you can configure this yourself in VSCode settings until it gets added as a default:

```json
	"workbench.editorAssociations": {
		"*.db": "sqlite-viewer.view"
	},
```

**Comment by deadcoder0904** [comment]
@qwtel would love this as default.

can you release a new version after merging https://github.com/qwtel/sqlite-viewer-vscode/pull/8?

**Comment by qwtel** [comment]
I was reluctant to make this the default, since `.db` is such  a generic name that it could be referring to any database format.
In practice, it seems to be mostly sqlite, so I've now made this default in v0.4.0+.

**Comment by turbotimon** [comment]
> I was reluctant to make this the default, since `.db` is such a generic name that it could be referring to any database format. In practice it seems to be mostly sqlite, so I've now made this default in v0.4.0+.

@qwtel there is the option to [check the Magic Header String (see 1.3.1)](https://www.sqlite.org/fileformat.html). Here is an example of another extension that does this: https://github.com/optuna/optuna-dashboard/blob/7f92e0654fffeb5f6ba0cdb26d1125deee1a5bd6/optuna_dashboard/_storage_url.py#L62-L69
