### ISSUE TITLE
Sort tables alphabetically

### ISSUE THREAD

**Issue by a-was** [qwtel/sqlite-viewer-vscode#32]
I have some databases with a lot of tables, it would be a lot easier to work with them if the tables were sorted by name. Currently, the names are random. Whenever I want to find some table, I have to read them all and find desired one...

Some example db:

![pic](https://github.com/qwtel/sqlite-viewer-vscode/assets/44528455/0a612be2-12d5-46eb-885b-8f652761159d)

**Comment by qwtel** [comment]
The order was based on the default for `main.sqlite_schema`, which seems to be "last changed". I've changed it to alphabetical order v0.4.11
