### ISSUE TITLE
Reading Data In Wal Mode

### ISSUE THREAD

**Issue by sahin52** [qwtel/sqlite-viewer-vscode#35]
I created a new sqlite db with C# .Net Core EF Core.  
I can add/read data without a problem. But much of the data is not shown in this extension, because the db is in WAL mode.
![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/39086573/2b413b17-2e38-4c91-bf22-2dcceed71a77)

I can read data with sqlite3 cli (https://sqlite.org/download.html -> sqlite-tools-win32-x86-3430100.zip)
![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/39086573/4135ea65-1f5b-4bd0-a296-0b20966e8f94)
But the data is old in this extension because of WAL mode
![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/39086573/97708ad7-a925-456e-81a6-afe57c31533e)

I couldnt figure out how to disable wal mode either

**Comment by sahin52** [comment]
I found a solution, but the issue still continues.
For the people with the same problem,
go to sqlite cli tool, or any other tool that you can write sql commands
Run this command: 
```  PRAGMA journal_mode=DELETE; ```
The sqlite database will turn into delete mode, which will disable wal and shm files

**Comment by pekeler** [comment]
Same. I wish this plugin supported reading DBs with WAL.

**Comment by git-nico** [comment]
Yes, WAL support would be greatly appreciated

**Comment by dourgulf** [comment]
Yes, want WAL support!

**Comment by qwtel** [comment]
> I wish this plugin supported reading DBs with WAL.

I wish it did too lol. Unfortunately it's not a simple fix. I've written down what I know in a Discussion in case someone wants to get into the technically nitty-gritty: https://github.com/qwtel/sqlite-viewer-vscode/discussions/55

**Comment by qwtel** [comment]
I found a mostly simple fix after all. You can try it out using the v0.5.0 pre-release. You'll have to go to extensions, find SQLite Viewer and click "Switch to Pre-Release Version". 

Please let me know if you encounter any issues. If it works as expected, please give this post a thumbs up.

Getting this to work required quite a bit of restructuring as well as a custom SQLite VFS. There's potential for some unforeseen breakage.

<img width="609" alt="Screenshot 2024-05-18 at 23 59 59" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/37b4652c-a3d1-45f0-a32a-4371b9aecdd2">

**Comment by qwtel** [comment]
Shipped on main channel in v0.5.5
