### ISSUE TITLE
Using a column name which contains '.', the values of that column are shown as NULL.

### ISSUE THREAD

**Issue by Diego-0110** [qwtel/sqlite-viewer-vscode#38]
**Version**: v0.14.1
```python
import sqlite3

conn = sqlite3.connect('test.sqlite')

conn.execute('''CREATE TABLE Test (
                  Id INTEGER PRIMARY KEY,
                  "Name." TEXT
              )
              ''')

conn.execute('''INSERT INTO Test (Id, "Name.") VALUES (?, ?)''', [1, 'Name1'])

conn.commit()

rows = conn.execute('SELECT "Name." FROM Test')

print(rows.fetchall())
```

The output confirms that "Name." column exists and has one value, but the SQLite Viewer Extension shows just NULL value.
```bash
[('Name1',)]
```

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/100482920/178fabc1-82ba-479d-a4dc-fc89543f4ab4)

**Comment by qwtel** [comment]
Cannot reproduce in v0.4.2. Might have been an issue with an earlier version of the extension.

<img width="897" alt="Screenshot 2024-05-01 at 17 53 53" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/c5207e05-81ae-4f26-8a9e-692dd4d7d0c7">
