### ISSUE TITLE
Feature Request: Allow configuring extensions to view

### ISSUE THREAD

**Issue by xyzshantaram** [qwtel/sqlite-viewer-vscode#4]
Currently, we can only open `.sqlite` and `.sqlite3` files. It would be helpful to be able to configure the viewer to also open other extensions, such as `.db`.

**Comment by qwtel** [comment]
you can,  please see gif in changelog for details.

**Comment by xyzshantaram** [comment]
Awesome, thanks a lot! This extension is everything I needed!

**Comment by arnonrdp** [comment]
Nice! I just came here with the same issue and it's already resolved!
Thanks guys!
🚀
