### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by proof-llc** [qwtel/sqlite-viewer-vscode#40]
Thank you for this project!

when i clone the project, i get a permission error: `git clone --recurse-submodules -j8 https://github.com/qwtel/sqlite-viewer-vscode.git`

```
Submodule 'sqlite-viewer-app' (git@github.com:qwtel/sqlite-viewer-app.git) registered for path 'sqlite-viewer-app'
Cloning into './sqlite-viewer-vscode/sqlite-viewer-app'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

It appears that qwtel/sqlite-viewer-app is a dependency that is not accessible. Would you consider making it publicly accessible?

**Comment by qwtel** [comment]
> Would you consider making it publicly accessible?

I'm considering it, but not in its current state.
