### ISSUE TITLE
Could not get updated database contents 

### ISSUE THREAD

**Issue by Lynnes001** [qwtel/sqlite-viewer-vscode#41]
Great tool! Saves lots of time.

I use the terminal to create new .sqlite files in my project folder, however, i could no see anything from the extension. I will have a reopen the vscode and see the update-to-date tables/contents? Could it be cache issue probably?

**Comment by qwtel** [comment]
Not sure what `vscode.fs` does under the hood. The refresh button in the viewer itself should reload the contents of a file. If the file is not showing in the file explorer its out of my control/vscode related.
