### ISSUE TITLE
how show utf-8 character

### ISSUE THREAD

**Issue by SunYong0821** [qwtel/sqlite-viewer-vscode#43]
![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/7601063/e1c13a21-aec0-47bc-811c-242c8ca4e297)

**Comment by qwtel** [comment]
Could have been an issue with a previous version of the extension, or an encoding issue with that particular file. It is showing unicode characters in v0.4.2:
<img width="1053" alt="Screenshot 2024-05-01 at 17 26 51" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/a443d5b9-226e-45bd-9247-d1bdeb726aa9">
