### ISSUE TITLE
Show sqlite_master table

### ISSUE THREAD

**Issue by UltimatePea** [qwtel/sqlite-viewer-vscode#44]
Is there a way to view/introspect the `sqlite_master` table?

**Comment by qwtel** [comment]
Not quite what was requested here, but the v0.6.0 pre-release has a side bar that shows this info:

<img width="407" alt="Screenshot 2024-06-10 at 13 12 37" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/918317be-5e50-41df-8b68-c35371282f2c">
