### ISSUE TITLE
Add .db file support

### ISSUE THREAD

**Issue by SH20RAJ** [qwtel/sqlite-viewer-vscode#45]

**Comment by turbotimon** [comment]
I like the simplicity and clean UI of this extension. However my sqlite db have normally `.db` ending for compatibility with other tools. So I really would like to have this option.

To check if it compatible, we could check the [Magic Header String (see 1.3.1)](https://www.sqlite.org/fileformat.html) of a `.db` file: *"SQLite format 3\000"*

**Comment by turbotimon** [comment]
dublicate #31

**Comment by qwtel** [comment]
Added in v0.4.0
