### ISSUE TITLE
Error: Website Issues or Moved

### ISSUE THREAD

**Issue by Dkilg2024** [qwtel/sqlite-viewer-vscode#46]
SQLite Viewer is installed but not working. 

When I hover over the space, the following error appears: 
It looks like the webpage might be having issues, or it may have moved permanently to a new web address.

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/161845133/1bdea52d-f042-4fbf-91ab-29a960d63387)

**Comment by qwtel** [comment]
Must have been a temporary issue with ms/githubusercontent or something is blocking external resources.
