### ISSUE TITLE
Can we use filters find exact match?

### ISSUE THREAD

**Issue by FelixHSS** [qwtel/sqlite-viewer-vscode#47]
For example, I want to find an entry has ID = 1. If I filter the column use 1, then the result will inculde all entries with ID contains 1, like 214.

**Comment by qwtel** [comment]
Shipped in v0.4.6 

This button makes the filter an exact match:

<img width="419" alt="Screenshot 2024-05-04 at 11 38 01" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/6f152e81-5705-4df8-841f-4f6bbbb49ff3">
