### ISSUE TITLE
Could you make fields that were defined with JSON type display as a text area instead of text field?

### ISSUE THREAD

**Issue by treeder** [qwtel/sqlite-viewer-vscode#49]
Hard to view the data in a single row text field:

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/75826/e7442bf3-dd75-4db7-8065-7e6665adcb69)

**Comment by qwtel** [comment]
Yes

**Comment by qwtel** [comment]
Shipped in v0.4.4+

**Comment by treeder** [comment]
Wow, you rock. Thanks for the quick turnaround.

**Comment by qwtel** [comment]
Consider leaving a 5 star review: https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer&ssr=false#review-details
