### ISSUE TITLE
SQLITE_NOTADB: sqlite3 result code 26: file is not a database

### ISSUE THREAD

**Issue by SamPosh** [qwtel/sqlite-viewer-vscode#51]
I could not open SQLITE db in sqlite viewer since today morning.
Seems like there is an update happened

The error is
SQLITE_NOTADB: sqlite3 result code 26: file is not a database

When I downloaded the DB and open it from DB browser or sqlite viewer webapp it works. So there is no problem with db itself

**Comment by florian-imi** [comment]
Please provide an example db file and the version of the extension.

Downgrading to the latest non-prerelease version should fix it in the meantime:

<img width="322" alt="Screenshot 2024-05-06 at 14 12 16" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/108846768/f8426399-eb2d-43ad-89a5-f6e8c5f3b417">
<img width="250" alt="Screenshot 2024-05-06 at 14 12 51" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/108846768/b8371079-7887-47d6-b1a5-d30e0e0b4251">

**Comment by qwtel** [comment]
Can you provide an example file and/or determine which version introduced this behavior? 

<img width="322" alt="Screenshot 2024-05-06 at 14 12 16" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/6521b63b-1ded-4143-b1c8-a1da19b5f13a">

**Comment by SamPosh** [comment]
My version of sqlite viewer is v0.4.8

vscode version detail is as below
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by qwtel** [comment]
Hard to reproduce without a sample file. Can you downgrade to v0.4.6 and confirm if it still worked there?

**Comment by qwtel** [comment]
Fixed in v0.4.9
