### ISSUE TITLE
SQLite can't see any of my tables, even after refreshing (0.4.10)

### ISSUE THREAD

**Issue by axefrog** [qwtel/sqlite-viewer-vscode#56]
[xf.zip](https://github.com/qwtel/sqlite-viewer-vscode/files/15302329/xf.zip)

I've attached a database with 3 tables I've created. They're definitely there because I can access them from code, but SQLite Viewer shows 0 tables, and after clicking refresh it still shows 0 tables.

**Comment by qwtel** [comment]
Unfortunately that zip archive is empty.

Regarding your issue, could it be that the db in WAL mode? The extension currently can't show the contents of the -wal file (see #35, project readme).

**Comment by axefrog** [comment]
@qwtel Ahh! That would make sense. Yes I'm using WAL mode. I'll check out the link, thanks.

**Comment by qwtel** [comment]
You could try again with the latest pre-release 0.5.0 (will have to go to extensions, find sqlite viewer and click "switch to pre-release version". If you do, please let me know if you encounter any issues.
