### ISSUE TITLE
Cannot see views.

### ISSUE THREAD

**Issue by grahamjenson** [qwtel/sqlite-viewer-vscode#59]
I cannot see sql views that I have created, it would be very useful for my usecase.

**Comment by qwtel** [comment]
Coming soon

**Comment by qwtel** [comment]
Shipped in v0.5.9 

***

I've your happy with SQLite Viewer, consider leaving a 5-star review at https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer&ssr=false#review-details

**Comment by grahamjenson** [comment]
Awesome, thank you!
