### ISSUE TITLE
Doesn't work in Project IDX (Google's IDE)

### ISSUE THREAD

**Issue by treeder** [qwtel/sqlite-viewer-vscode#60]
https://idx.google.com/

Probably related to this: https://github.com/qwtel/sqlite-viewer-vscode/issues/36

**Comment by treeder** [comment]
Looks like an old version on open vsx:

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/75826/e70f2020-4895-4339-b410-5c0739904fcb)

**Comment by qwtel** [comment]
Something strange going on here, actually don't think this is related to #36. 

For some reason, it's not showing new versions, but they're definitely published. It's even showing the latest version before installation.

After some investigation my current best guess is that it's the minimum vscode requirement. I've bumped that 1.85.0 with the 0.4.0 release, which is the first version that's missing, and IDX seems to be based off of vscode 1.81.0. 

The requirement is  pretty arbitrary, so I'm gonna reset it to something like 1.81.0 in the next release, let's see if that helps.

**Comment by qwtel** [comment]
> my current best guess is that it's the minimum vscode requirement

That was it, but it's still not working due to content security policy. IDX, GitPod, and possible others aren't setting a wide enough value for `Webview.cspSource`. Gonna limit the CSP to known envs in the next minor bump.

**Comment by qwtel** [comment]
Fixed in v0.5.8 

<img width="1464" alt="Screenshot 2024-06-11 at 14 46 37" src="https://github.com/qwtel/sqlite-viewer-vscode/assets/951987/487c9e92-1537-4ef3-bad3-f969254d5108">

**Comment by treeder** [comment]
Nice, thanks!
