### ISSUE TITLE
Applying then removing filter on one column causes rows with NULL in that column to disappear

### ISSUE THREAD

**Issue by EVERYTHING-NOT-AVAILABLE** [qwtel/sqlite-viewer-vscode#65]
until the file is closed and re-opened, in both v0.5.8 and v0.6.2.

By the way, it would be nice if there is a way to filter for NULL values.

**Comment by qwtel** [comment]
Fixed in 0.5.9 and 0.6.3 (pre-release).

Also added a button to filter NULL-ish values (NULL and empty string). You can now also type `NULL` or `''` into the search bar to filter by NULL values or empty strings specifically.
