### ISSUE TITLE
UI crash if function is not found

### ISSUE THREAD

**Issue by chgeo** [qwtel/sqlite-viewer-vscode#66]
The UI crashes if an unknown function is used in a view definition:

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/7470719/16b0e007-69d2-434e-9d29-8a34931c1d47)

I would expect that it only fails for the affected views, but still shows the rest.
This is what an IntelliJ plugin does in this case:

![image](https://github.com/qwtel/sqlite-viewer-vscode/assets/7470719/09ce29bc-5504-423b-94a0-7f9c1cd45ea5)

See this sqlite file for an example: 
[db.sqlite.zip](https://github.com/user-attachments/files/16069222/db.sqlite.zip) (unzip it)

**Comment by qwtel** [comment]
> I would expect that it only fails for the affected views, but still shows the rest.

That's the right thing to do. Fixed it in v0.5.10 (main line)

Thanks for the example file, that helped a lot.
