### ISSUE TITLE
Stop showing the  WAL mode databases notification

### ISSUE THREAD

**Issue by MetRonnie** [qwtel/sqlite-viewer-vscode#68]
Every time I open an sqlite DB I get this notification:

> SQLite Viewer now supports reading WAL mode databases. Check out the Changelog for details.

I think this should only show up **once** when you install the extension, if at all.

**Comment by qwtel** [comment]
> I think this should only show up once when you install the extension, if at all.

Indeed, that's how it's supposed to work 😐  Fixed in 4fd42298e0e4075918d966a87d68e6844268d43b
