### ISSUE TITLE
unable to view tables with certain characters in column names

### ISSUE THREAD

**Issue by Heiner92** [qwtel/sqlite-viewer-vscode#71]
It seems that some characters are not supported inside column names. 

`SQLITE_ERROR: sqlite3 result code 1: unrecognized token: "]"`

Maybe special characters need to be escaped inside the performed sql queries? I did not check the source code yet, but I guess it could be a quick fix :)

So far I did not face this issue with the same data in other viewers or db-managament software.

**Comment by qwtel** [comment]
Thanks for reporting this. This should be fixed in 0.5.12
