### ISSUE TITLE
extension locks files even after the view is closed (windows)

### ISSUE THREAD

**Issue by kaminskypavel** [qwtel/sqlite-viewer-vscode#72]
Hey, first of all - great extension! really 10x my productivity 👍

the issue im having is (as described in the title), even when the view is closed, i cannot update/delete the file since its getting locked 
with `python.exe`, so i have to manually kill the process first.

![image](https://github.com/user-attachments/assets/0ee3d3d8-fd21-4449-b6f3-c574c7762e74)

**Comment by qwtel** [comment]
this extension is not using python or locking files for that matter

**Comment by kaminskypavel** [comment]
:/ sorry about that
