### ISSUE TITLE
Dont open .sqlite

### ISSUE THREAD

**Issue by IlianL** [qwtel/sqlite-viewer-vscode#74]
After opening db i just had an empty page. It seems problem on my side, I just created test .sqlite db and had an empty page again. 
Edit: after reinstallation vscode everything works.
[db_video.zip](https://github.com/user-attachments/files/17472868/db_video.zip)
![image](https://github.com/user-attachments/assets/61cc4927-7f63-4d5e-9958-51f288bbb88f)

**Comment by qwtel** [comment]
Could you share a minimal .sqlite file that reproduces the issue?  Include in issue or send to mail@sqliteviewer.app
