### ISSUE TITLE
Error when trying to open seqlite file (> 2GB)

### ISSUE THREAD

**Issue by stephwon** [qwtel/sqlite-viewer-vscode#76]
I get an error message when opening the `.sqlite` file (12GB).
I adjusted the max file size at settings, but still getting error messages...
Does the extension not work on a file size greater than 2GB?
Can the extension be used to look at large sqlite files?

**Comment by stephwon** [comment]
![Screenshot 2024-10-23 at 11 22 33 PM](https://github.com/user-attachments/assets/36e4cf68-bd20-45e9-92a8-ae689ad5bd62)

**Comment by qwtel** [comment]
Duplicate #57
