### ISSUE TITLE
Cannot view database without file extension

### ISSUE THREAD

**Issue by MetRonnie** [qwtel/sqlite-viewer-vscode#78]
1. Rename an sqlite database to `foo.txt`
2. Drag and drop into VSCode and choose to open it in sqlite-viewer - this works
3. Close it and rename to `foo`
4. Try to open it again - I just get a blank view with no tables

Tested on Windows and Linux with v0.8.8

This is possibly what I was actually running into when I reported #64

**Comment by qwtel** [comment]
Ah, that makes sense. Sounds plausible, I'll take a look. Thanks for looking a closer look.

**Comment by qwtel** [comment]
It was the combination of hidden folder + no file extension. Will roll out a fix shortly.
