### ISSUE TITLE
Row resolution of a View limited to 300 rows

### ISSUE THREAD

**Issue by puppyworldyes** [qwtel/sqlite-viewer-vscode#79]
While using the experimental Views feature, SQLite Viewer for VS Code (free version) will not resolve/render more than 300 rows.

The database consists of two tables and a view. Its size is 250 MB. Visual Studio Code max file size was increased to 1,000 MB. SQLite Viewer will show both tables (1,500,000 rows and 20,000 rows), but only shows the first 300 rows of the view (20,000 rows).

Is there an extension setting or Visual Studio Code setting to increase to see all the expected rows? After resolving/rendering the first 300 rows it still shows "(loading...)" and Code Helper (Plugin) is using 100% CPU.

SQLite Viewer for VS Code (free) version 0.8.8 
Visual Studio Code version 1.95.0
Node.js version 20.18.0
macOS version 13.5
System memory 32 GB

**Comment by qwtel** [comment]
> 300 rows it still shows "(loading...)" and Code Helper (Plugin) is using 100% CPU.

Ah, yes, I almost didn't release the Views panel for this reason. It's essentially a hack that needs to assign a canonical row number to each row in the view, so it slows with size of the view. 20,000 rows is not an issue in general, but perhaps the query runs long for other reasons. The only thing that's odd is that it can show the first 300 rows. If you could share the db file, I could investigate it.
