### ISSUE TITLE
[Improvement] Could you change the SQL field in the Table Info tab of the Secondary Sidebar from a singleline to a resizeable multiline text field?

### ISSUE THREAD

**Issue by anotherssa** [qwtel/sqlite-viewer-vscode#80]
Currently it looks like this:
![image](https://github.com/user-attachments/assets/94630761-448b-4daf-b01c-767ece359803)
Changing it to a multiline text field seems like an easy thing to do which should make it much more user friendly.

**Comment by qwtel** [comment]
SQLite simply returns the create statement as it was entered. If it was a one-liner, that's what's going to show up in the UI. What's needed here is formatting of the SQL statement, switching to a textarea by itself won't help much. I've added it in 0.9.4
