### ISSUE TITLE
The database table created with df.to_sql() in pandas cannot be displayed normally

### ISSUE THREAD

**Issue by lambda-wiki** [qwtel/sqlite-viewer-vscode#9]
Thanks to your great job first! 
The problem is the database table created with df.to_sql() in pandas cannot be displayed normally,like the picture fellow.
<img width="729" alt="1" src="https://user-images.githubusercontent.com/98476840/164750746-b7e830bd-223c-4295-9add-fe54cb4a205b.png">
<img width="912" alt="2" src="https://user-images.githubusercontent.com/98476840/164750758-fb6fab7d-a1b2-4b7a-933a-f84601b2bd91.png">

**Comment by qwtel** [comment]
Should be fixed in latest prerelease 0.2.1
